# Generated by Django 4.2.15 on 2024-09-02 17:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_details', '0002_subscriber_delete_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', ckeditor.fields.RichTextField()),
                ('recipients', models.ManyToManyField(to='home_details.subscriber')),
            ],
        ),
        migrations.DeleteModel(
            name='MailMessage',
        ),
    ]
