# Generated by Django 4.2.15 on 2024-09-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_view_own_booking', 'Can view own booking'), ('can_edit_own_booking', 'Can edit own booking'), ('can_delete_own_booking', 'Can delete own booking')]},
        ),
    ]
